<<<<<<< HEAD
# Site settings
title: WebConfs - A blog about web conferences
email: coolwebconfs@gmail.com
description: A blog about my favorite web conferences.
url: "http://webconfs.me" # the base hostname & protocol for your site
twitter_username: guilh
=======
---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
>>>>>>> origin/gh-pages

'
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
<<<<<<< HEAD
permalink: /:title
=======
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
>>>>>>> origin/gh-pages
